### ISSUE TITLE
Unofficial version of plugin overwrites the official one

### ISSUE THREAD

**Issue by jtabox** [Akurosia/MyCustomDalamudPluginRepoCollection#11]
There's a new entry in this repo collection, a chinese plugin that's an unofficial version of MaterialUI. The issue is it has a higher version than the official one, so it will get auto-installed. It turns MaterialUI to chinese user interface and it's of course not sanctioned from the original MaterialUI's creator. This happens if you have Akurosia's repo and the official MaterialUI repo.

Not sure how to explain it better, this screenshot shows the issue:
https://i.imgur.com/zkWawTo.png

The only solution I could find is to either disable Aku's repo completely or disable auto-updating plugins when you log in. It's worth keeping this in mind, since someone could have their malicious plugin auto-installed this way.

**Comment by Akurosia** [comment]
i temporarly removed the repo. just uninstall and reinstall the plugin and it should be back to normal. i will check if i find a workaround to seperate chinese repos somewhat from globals ones. Only issue is, that i want to be able to support beta versions and dont have the same entry 4-5 times in the list.

**Comment by jtabox** [comment]
Ah alright, thanks for quick action. I had edited xivlauncher files manually to make the official version seem higher than the chinese one's, temporarily :D I'll just un- and reinstall now.
But yeah there isn't much you can do, unless you do such manual work. It's the addon creators that shouldn't be using the exact same name, otherwise this happens. In general, there's quite a few chinese ones that are pretty good so it would be a pity to outright remove them. And tbh I posted this mostly so people keep an eye on their plugins.
For example I now realized ReAction also gets replaced by an unofficial alternative. Someone made a fork with version v.69.1.6.4 (the official is 1.1.6.4). Which means even if the original creator publishes an update, the fork will still have prio and you won't be notified.
The best option would be for XIVLauncher to allow us to "blacklist" specific versions or something similar, but since the whole thing is about 3rd party plugins there's no room for such a suggestion.
Also, thanks for your repo, there's always some interesting plugin that shows up and is worth trying :D
