### ISSUE TITLE
Please replace Customize+ fork repo with main repo.

### ISSUE THREAD

**Issue by Phenrei** [Akurosia/MyCustomDalamudPluginRepoCollection#12]
Not sure if this was going to potentially happen automatically, but https://raw.githubusercontent.com/Maxunit/MyDalamudPlugins/master/pluginmaster.json in the repo list is a fork of the official at https://raw.githubusercontent.com/XIV-Tools/DalamudPlugins/main/repo.json we had up overnight before I could push the proper version which got picked up into the list. The latter is sure to be the correct code for Customize+.

Appreciate the list as I've found a lot of neat things through it myself, just want to make sure my own plugin is properly represented. Thanks.

**Comment by Akurosia** [comment]
I added the offical repo now and if the version is higher than the forks version, the official one should be found in dalamud.
