### ISSUE TITLE
TextAdvance isn't available anymore?

### ISSUE THREAD

**Issue by Battler624** [Akurosia/MyCustomDalamudPluginRepoCollection#13]
The whole repo of Eternita-S isn't available anymore, is there a reason why?

https://raw.githubusercontent.com/Eternita-S/MyDalamudPlugins/main/pluginmaster.json

its available in repo_urls but not in ffxiv_custom_repo

**Comment by Akurosia** [comment]
The Eternita-S repo is in the 'ffxiv_custom_repo.json' file but i also realised, that i dont see them in dalamud itself. tbh i dont know why currently. But even if i add your mentioned repo manually into my dalamud, i dont see eternitas plugins at all.

**Comment by Battler624** [comment]
apologies I see it in the  the custom repo json but not ingame, but if I add the URL above plugmaster.json it works.

BTW it was working fine 2 days ago

**Comment by Akurosia** [comment]
github seams to sometimes not returning the data for my script thats why they are sometimes removed for a while. i am currently checking if i can get around that issue.

**Comment by Battler624** [comment]
Weird issue, maybe move the list to gitlab?

Because today eternita is showing up but unknownx isn't (noclippy), well eitherway, thanks for this. saves much headache.

**Comment by Akurosia** [comment]
The problem is with the lists where the data is coming from. It should keep track of all existing projects once they are added for now

**Comment by Akurosia** [comment]
ok ive done a new run manually and its added now (and hopefully should stay added...

```
Work on repo: https://raw.githubusercontent.com/UnknownX7/DalamudPluginRepo/master/pluginmaster.json
        New Cammy [Aku API 7] '2.0.3.5' '1'
        New Fractionality [Aku API 7] '1.0.1.3' '1'
        New DalamudRepoBrowser [Aku API 7] '2.0.1.1' '1'
        New NoClippy [Aku API 7] '0.4.0.12' '1'
        New OOBlugin [Aku API 7] '1.1.2.7' '1'
        New ReAction [Aku API 7] '1.1.6.6' '1'
```

**Comment by Battler624** [comment]
thank you, i'll recheck whenever i have the chance.
