### ISSUE TITLE
Avarice not updating.

### ISSUE THREAD

**Issue by Battler624** [Akurosia/MyCustomDalamudPluginRepoCollection#16]
Avarice, a plugin by Puni.sh, is not getting updated.

**Comment by Akurosia** [comment]
Currently i get an error when handling the json, will check later today what the issue is.

**Comment by Battler624** [comment]
> Currently i get an error when handling the json, will check later today what the issue is.

Issue was fixed with https://github.com/Akurosia/MyCustomDalamudPluginRepoCollection/commit/a17720d93822e8aad760bf6d694e9b46a46e14d8

idk why but your repo took 2 days to get updated.

**Comment by Akurosia** [comment]
it was a code issue with my script. somehow something changed in the puni repo which triggered an error that has not happend before
