### ISSUE TITLE
Versioning issue

### ISSUE THREAD

**Issue by Aireil** [Akurosia/MyCustomDalamudPluginRepoCollection#20]
Hey, I just got an issue with my plugin [FFLogsViewer](https://github.com/Aireil/FFLogsViewer) on your repo. It updated to the Chinese version, maintained on this repo: https://raw.githubusercontent.com/NukoOoOoOoO/DalamudPlugins/dev/pluginmaster.json
However, it's not just that, it also turns out the previous version of my plugin in your list was 2.0.6.2, which is an outdated 6-month-old update.

I don't particularly care if people are using your repo to install the plugin, however, I would like that only my repo update it in your list. Is that something you think you could add? Having a matching internal name <=> repo(s) that are allowed to be updated from.
This would not only avoid accidental updates (like this one), but also malicious ones, should someone want to hijack my plugin from your repo.

I updated my repo to 2.0.8.1 to fix that Chinese version issue, not sure if it's going to update your list, as the previous version was quite old.

**Comment by Akurosia** [comment]
I am currently rewriting the whole script, as it has some strange issues like the not updateing one. During running it finds the new version, but for whaever reason still picks the old one. I tried manually fixing it for the moment, but a rewrite is needet to avoid issues like this in the future.

EDIT: For the collision problem, its always hard to make decisions. The original intend was to have a single repo i can share with frieds to reduce the amount of repos they have to enter in and always stays uptodate.
Locking plugins to a single repo CAN result in abandond repositories that others picked up again (like JobIcons) which in the end would not end up in my list.

On the other hand i can understand your issue (and in my opinion i think they should pick a different internal name like FFLogsViewerCN to avoid situations like this). For very few entries i have hardcoded rules (e.g. Penumbra) but i want to keep them as few as possible for the above mentioned reason. For the time beeing i will add a rule and see if i can maybe find a better way to handle it in the future

**Comment by Aireil** [comment]
It seems like it picked up the old version again, but it looks like it's getting it from this repo: https://raw.githubusercontent.com/IKDprogram/pluginsJson/main/plugin.json
Not sure what is this repo, looks like it's just an aggregated list again, it even has an `Aku API 5` plugin lol.

I agree that choosing different internal names would probably have been a good idea, never thought it would cause issues to be fair.

I do still think anyone being able to update a plugin people think under my name to be an issue, because clearly people don't realize they're not actually getting updates from me: https://github.com/Aireil/FFLogsViewer/issues/27
Should any malicious actor want to update my plugin to do nasty things, I wouldn't be surprised if people using your list think that the update comes from me.
This is why I'm kind of split on mega repos, people can take the (increased) security risk for themselves, but I can see how it can fall on me if anything happens with my plugin.

**Comment by Akurosia** [comment]
The issue here is that not every user has github name equals the Author field (or any other field) espacially when its a fork that adds new functionality etc.

i changed up my script now as relaying on the repourl field was not good enough. Hope this is now resolved x.x

**Comment by Aireil** [comment]
Looks like it has the proper version now, so closing this.
