### ISSUE TITLE
Don't mix old API / Dalamud CN plugins with Global

### ISSUE THREAD

**Issue by reiichi001** [Akurosia/MyCustomDalamudPluginRepoCollection#8]
The title kinda says it all.

You're pulling in a bunch of plugins that will never run on a modern version of Dalamud, and if forced, will probably just crash the game or behave erratically.

Anything less than API 6 is either horrendously out of date or broken. 

Anything made for Dalamud CN will crash on on the Global FFXIV client if it relies on opcodes, hooks, sigs, or Chinese-only regex parsing, and vice-versa, Global client plugins are not designed for Dalamud CN or the China/Korea clients and may break because they cannot assume the same information is in the same places.

Users should be encouraged to use the actual custom repo from the developer making the unofficial plugin anyways, as they usually state if/where they provide support and other instructions that may be relevant to using the plugin.

**Comment by Akurosia** [comment]
Nobody is forced to use my custom repo and its mostly made for my closer friends and myself to not worry about sending 20-30 links to every new user.

Everything that isn't >= latest specified api version (currently 6) will not be added by my script so outdated plugins will not appear there. The outdated wouldn't also be just a problem by this repo, but for ANY single repo you could find as every project can be abandond by the creator and might not work when a game update is released (e.g. opcode changes etc)

There are several plugins written by chinese players that will also work on the global version (ofc not all of them will) but why should i filter them out? Maybe some chines/korean guys use this repo as well as there will be a lot of plugins working on multiple versions depending on the creator/opcodes/regex etc.

**Comment by slotthhy** [comment]
What a ridiculous take. You do know that this repo simply existing is reason for people to use it? Saying [Aku API 7] doesn't magically make a plugin compatible with API 7, but people think it does because it shows up on the third-party repo browser. You're just distributing broken software to people who then come to the Dalamud maintainers for help.

**Comment by Akurosia** [comment]
> What a ridiculous take. You do know that this repo simply existing is reason for people to use it? Saying [Aku API 7] doesn't magically make a plugin compatible with API 7, but people think it does because it shows up on the third-party repo browser. You're just distributing broken software to people who then come to the Dalamud maintainers for help.

My script will only add plugins that match the version i set it to. So once i change it to 7 only api7 things are added and everything lower will be discarded. 

EDIT: Now the file only contains valid api7 version
